[package]
name = "filetruck"
version = "0.1.0"
authors = ["Eamonn Laffey <eamonn.laffey@gmail.com>"]
edition = "2018"

[dependencies]
argh = "0.1.7"
serde = {version = "1.0.133", features = ["derive"]}
serde_yaml = "0.8.21"
same-file = "1.0.6"
termcolor = "1.1.2"
atty = "0.2.14"

